spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true   # Live Reload
  datasource:
    url: jdbc:mysql://localhost:3306/kkamji_db?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 연결 설정
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace