spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 연결 설정
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: validate
#server:
#  port: 80    # 애플리케이션 포트 설정